// ignore_for_file: public_member_api_docs, sort_constructors_first
// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'charity_model.mapper.dart';


@MappableClass()
class CharityModel with CharityModelMappable {
  
  CharityModel({
    required this.charityId,
    required this.charityNumber,
    required this.charityName,
    required this.role,
    required this.charityLat,
    required this.charityLang,
    required this.totalServices,
  });

  @MappableField(key: 'charity_id')
  final String charityId;

  @MappableField(key: 'charity_number')
  final String? charityNumber;

  @MappableField(key: 'charity_name')
  final String charityName;

  final String? role;

  @MappableField(key: 'charity_lat')
  final double charityLat;

  @MappableField(key: 'charity_lang')
  final double charityLang;

  @MappableField(key: 'total_services')
  final int totalServices;


}
