// ignore_for_file: public_member_api_docs, sort_constructors_first
// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'complaint_model.mapper.dart';

@MappableClass()
class ComplaintModel with ComplaintModelMappable {
    ComplaintModel({
    required this.complaintId,
    required this.userId,
    required this.charityId,
    required this.requestId,
    required this.driverId,
    required this.hospitalId,
    required this.complaint,
    required this.response,
    required this.isActive,
  });
  
  @MappableField(key: 'complaint_id')
  final String complaintId;

  @MappableField(key: 'request_id')
  final String? requestId;

  @MappableField(key: 'user_id')
  final String? userId;

  @MappableField(key: 'charity_id')
  final String? charityId;

  @MappableField(key: 'driver_id')
  final String? driverId;

  @MappableField(key: 'hospital_id')
  final String? hospitalId;
  
  final String complaint;

  final String response;

  @MappableField(key: 'is_active')
  final bool isActive;

}
